{{- if and .Values.apiServer.enabled .Values.apiServer.service.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-apiserver
  labels:
    app: {{ $fullName }}-apiserver
    {{- with .Values.apiServer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if and (not (index .Values.apiServer.service.annotations "metallb.universe.tf/allow-shared-ip")) (eq .Values.konnectivityServer.mode "HTTPConnect") }}
    metallb.universe.tf/allow-shared-ip: {{ $fullName }}
    {{- end }}
    {{- with .Values.apiServer.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.apiServer.service.type }}
  {{- with .Values.apiServer.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
  - port: {{ .Values.apiServer.service.port }}
    name: client
    {{- with .Values.apiServer.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  {{- if and .Values.konnectivityServer.enabled .Values.konnectivityServer.service.enabled (eq .Values.konnectivityServer.mode "GRPC") }}
  - port: {{ .Values.konnectivityServer.ports.agent }}
    name: agent
    {{- with .Values.konnectivityServer.service.nodePorts.client }}
    nodePort: {{ . }}
    {{- end }}
  {{- end }}
  selector:
    app: {{ $fullName }}-apiserver
{{- end }}
