{{- if and .Values.konnectivityServer.enabled (eq .Values.konnectivityServer.mode "HTTPConnect") }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullName }}-konnectivity-server"
  labels:
    app: "{{ $fullName }}-konnectivity-server"
    {{- with .Values.konnectivityServer.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.konnectivityServer.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.konnectivityServer.replicaCount }}
  selector:
    matchLabels:
      app: "{{ $fullName }}-konnectivity-server"
  template:
    metadata:
      labels:
        app: "{{ $fullName }}-konnectivity-server"
        {{- with .Values.konnectivityServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.konnectivityServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.konnectivityServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.konnectivityServer.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if or .Values.konnectivityServer.affinity .Values.konnectivityServer.podAntiAffinity }}
      affinity:
        {{- with .Values.konnectivityServer.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if eq .Values.konnectivityServer.podAntiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "{{ .Values.konnectivityServer.podAntiAffinityTopologyKey }}"
              labelSelector:
                matchLabels:
                  app: {{ $fullName }}-konnectivity-server
        {{- else if eq .Values.konnectivityServer.podAntiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "{{ .Values.konnectivityServer.podAntiAffinityTopologyKey }}"
                labelSelector:
                  matchLabels:
                    app: {{ $fullName }}-konnectivity-server
        {{- end }}
      {{- end }}
      {{- with .Values.konnectivityServer.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
      {{ template "kubernetes.konnectivityServer.containers" . }}
      {{- with .Values.konnectivityServer.sidecars }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{ template "kubernetes.konnectivityServer.volumes" . }}
{{- end }}
