{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullName }}-scheduller"
  labels:
    app: "{{ $fullName }}-scheduller"
spec:
  replicas: {{ $.Values.scheduller.replicas }}
  selector:
    matchLabels:
      app: "{{ $fullName }}-scheduller"
  template:
    metadata:
      labels:
        app: "{{ $fullName }}-scheduller"
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - kube-scheduler
        - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
        - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
        - --bind-address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=true
        image: {{ $.Values.scheduller.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 15
        name: kube-scheduler
        resources:
{{ toYaml $.Values.scheduller.resources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: kubeconfig
          readOnly: true
      volumes:
      - secret:
          secretName: "{{ $fullName }}-scheduler-conf"
        name: kubeconfig
